FROM ballerina/ballerina:latest

COPY . /home/ballerina/international_delivery

WORKDIR /home/ballerina/international_delivery

# Switch to root for cleanup and build
USER root

RUN  bal build


# Switch back to ballerina user for running the service
USER ballerina

CMD ["bal", "run", "main.bal"]
